# Generated by Django 3.0.8 on 2021-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="ім'я")),
                ('dataSrc', models.CharField(max_length=150, verbose_name='посилання')),
                ('hashedpasword', models.CharField(max_length=16, verbose_name='хеш')),
            ],
            options={
                'verbose_name': 'користувач',
                'verbose_name_plural': 'користувачі',
            },
        ),
    ]
