# Generated by Django 3.1.7 on 2021-05-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesageString', models.TextField(max_length=3200, verbose_name='data')),
                ('owner1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own1', to='mkchat.users')),
                ('owner2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own2', to='mkchat.users')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чати',
            },
        ),
    ]
