# Generated by Django 3.1.7 on 2021-05-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0002_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='mesageString',
            new_name='mesagesList',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='owner1',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='owner2',
        ),
        migrations.AddField(
            model_name='chats',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mkchat.users'),
        ),
    ]
