# Generated by Django 3.1.7 on 2021-05-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0003_auto_20210503_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='mesagesList',
            new_name='mesageList',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='owner',
        ),
        migrations.AddField(
            model_name='chats',
            name='owner1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own1', to='mkchat.users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='owner2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own2', to='mkchat.users'),
        ),
    ]
