# Generated by Django 3.0.8 on 2021-05-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0004_auto_20210503_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='dataSrc',
            new_name='messageList',
        ),
    ]
