# Generated by Django 3.0.8 on 2021-05-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0005_auto_20210505_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='mesageList',
            new_name='messageList',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='messageList',
            new_name='dataSrc',
        ),
    ]
