# Generated by Django 3.0.8 on 2021-05-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0006_auto_20210505_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('chat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mkchat.Chats')),
            ],
        ),
    ]
