# Generated by Django 3.0.8 on 2021-05-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0007_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='messageList',
        ),
    ]
