# Generated by Django 3.0.8 on 2021-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0008_remove_chats_messagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.CharField(default='default !!!', max_length=300),
        ),
    ]
