# Generated by Django 3.1.7 on 2021-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0009_messages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default='98765432', max_length=8, verbose_name='токен'),
        ),
    ]
