# Generated by Django 3.0.8 on 2021-05-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0010_users_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dataSrc',
        ),
    ]
