# Generated by Django 3.0.8 on 2021-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0011_remove_users_datasrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hashedpasword',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='25f9e794323b453885f5181f1b624d0b', max_length=32, verbose_name='хеш'),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(default='25f9e794323b453885f5181f1b624d0b', max_length=32, verbose_name='токен'),
        ),
    ]
