# Generated by Django 3.1.7 on 2021-05-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkchat', '0013_auto_20210529_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='hashedpasword',
            new_name='password',
        ),
    ]
