# Generated by Django 3.0.9 on 2023-12-08 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mkchat', '0014_auto_20210529_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'повідомлення', 'verbose_name_plural': 'повідомлення'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='owner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='owner2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkchat.Chats'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
